apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp2
  template:
    metadata:
      labels:
        app: nodejsapp2
    spec:
      containers:
        - name: nodejsapp2
          image: robinnagpal/kubernetes-tutorial-003-node-app:latest
          env:
            - name: APP_NAME
              value: nodejsapp2

---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp2-service
spec:
  type: NodePort
  selector:
    app: nodejsapp2
  ports:
    - port: 3000
      targetPort: 3000
