
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: 519852036875.dkr.ecr.us-east-2.amazonaws.com/my-node.js-app:latest
          env:
            - name: nodeapp
              value: node

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 3000
      targetPort: 3000
